name: test
on: [push]
jobs:
  test-hwaccel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cpuinfo
        run: |
          cat /proc/cpuinfo
      - name: Configure
        run: |
          make allnoconfig
          sed -i -e 's/# CONFIG_SHA1_HWACCEL.*/CONFIG_SHA1_HWACCEL=y/' \
            -e 's/# CONFIG_SHA256_HWACCEL.*/CONFIG_SHA256_HWACCEL=y/' \
            -e 's/# CONFIG_SHA1SUM.*/CONFIG_SHA1SUM=y/' \
            -e 's/# CONFIG_SHA256SUM.*/CONFIG_SHA256SUM=y/' \
            .config
          grep SHA .config
      - name: Build
        run: |
          make -j $(nproc)
      - name: Test sha256sum
        run: |
          ulimit -c unlimited
          echo "core" | sudo tee /proc/sys/kernel/core_pattern
          ./busybox_unstripped sha256sum busybox_unstripped
      - name: find core dump
        if: ${{ failure() }}
        run: |
          cat /proc/sys/kernel/core_pattern
          sudo chmod +r core
      - name: Upload sha256sum core dump
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: coredump-sha256sum
          path: |
            core
            busybox_unstripped
      - name: Test sha1sum
        run: |
          for i in $(seq 0 99); do
            ./busybox sha1sum busybox_unstripped
          done
      - name: Upload sha1sum core dump
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: coredump-sha1sum
          path: |
            core
            busybox_unstripped
